# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.box = "mybox"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = 512
    vb.cpus = 2
  end
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y php5-cgi php5-cli php5-curl php5-common php5-gd php5-mysql
  SHELL
end
